### ISSUE TITLE
请问是用的D3那个版本呢?

### ISSUE THREAD

**Issue by willdx** [Youjingyu/web_mind_mapping#1]
你好！

最近在学习D3, 幸运的找到了你的项目, 我用的是3.5.17版本, 但是发现

```javascript
engine = d3.layout.tree().setNodeSizes(true);
```
中的setNodeSizes方法没有找到。

**Comment by Youjingyu** [comment]
我使用的是被第三方修改过的d3.js，在上面添加了setNodeSizes方法   
如果你要测试的话，用这个[d3.js](https://raw.githubusercontent.com/Youjingyu/web_mind_mapping/master/js/d3_flex_tree.js)吧

**Comment by willdx** [comment]
非常感谢！
